version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Manila
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      compatible-updates:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - security
