import test from 'node:test'
import assert from 'node:assert/strict'
import {readCatalogExport,previewCatalogImport,serializeCatalogCsv} from '../server/admin-bff/catalog-spreadsheet.js'
const row={catalog_id:'e74a4161-72ca-4d72-8f59-37aa690e1869',sku:'0000123',catalog_record_version:1,updated_at:'2026-10-03T00:00:00Z',name:'Synthetic Pasta'}
const csv=serializeCatalogCsv([row])
const client=result=>{const calls=[];const chain={select(...args){calls.push(args);return chain},order(){return chain},limit(){return Promise.resolve(result)}};return {calls,from(){return chain}}}
for(const [name,result,valid] of [['complete',{data:[row],count:1,error:null},true],['empty',{data:[],count:0,error:null},true],['truncated',{data:[row],count:2,error:null},false],['missing count',{data:[row],error:null},false],['null count',{data:[row],count:null,error:null},false],['null data',{data:null,count:0,error:null},false],['negative count',{data:[],count:-1,error:null},false],['fraction count',{data:[row],count:1.5,error:null},false],['duplicate SKU',{data:[row,{...row,catalog_id:'11000000-0000-4000-8000-000000000002'}],count:2,error:null},false],['duplicate catalog',{data:[row,{...row,sku:'other'}],count:2,error:null},false],['provider error',{data:[row],count:1,error:{message:'error'}},false],['over bound',{data:[row],count:1001,error:null},false]])for(const mode of ['export','preview'])test(`${mode} ${name}`,async()=>{const c=client(result);const run=()=>mode==='export'?readCatalogExport(c):previewCatalogImport(c,csv);if(valid){await run();assert.deepEqual(c.calls[0][1],{count:'exact'})}else await assert.rejects(run,/CATALOG_(EXPORT|PREVIEW)/)})
import {buildCatalogCommitPayload} from '../server/admin-bff/catalog-spreadsheet.js'
import {createHash} from 'node:crypto'
for(const [label,result] of [['capped',{data:[row],count:2,error:null}],['missing count',{data:[row],error:null}]])test(`commit ${label} refuses before payload creation`,async()=>{await assert.rejects(()=>buildCatalogCommitPayload(client(result),{csvText:csv,fileSha256:createHash('sha256').update(csv).digest('hex'),selectedRowNumbers:[2],reason:'Reviewed synthetic catalog correction.',operationId:'6a88b5f9-8be6-4f4d-a504-173c96f40df1',chunkIndex:0,finalChunk:true}),/CATALOG_PREVIEW_UNAVAILABLE/)})
const full=Array.from({length:1000},(_,i)=>({...row,sku:`S${i}`,catalog_id:`11000000-0000-4000-8000-${String(i).padStart(12,'0')}`}))
for(const mode of ['export','preview'])test(`${mode} full existing1000row bound`,async()=>{const c=client({data:full,count:1000,error:null});const result=mode==='export'?await readCatalogExport(c):await previewCatalogImport(c,csv);assert.ok(result);if(mode==='export')assert.equal(result.length,1000)})
