import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('launch migration contains atomic receiving and controlled transitions', async () => {
  const rawSql = await readFile(new URL('../supabase/migrations/20260803_launch_core_stabilization.sql', import.meta.url), 'utf8')
  const sql = rawSql.replace(/\r\n/g, '\n')
  expect(sql).toContain("alter type public.user_role add value if not exists 'Staff'")
  expect(sql).toContain("alter type public.channel_type add value if not exists 'website_retail'")
  expect(sql).toContain("alter type public.order_status_enum add value if not exists 'Packed'")
  expect(sql).toContain('create or replace function public.replace_product_batches')
  expect(sql).toContain('create view public.v_expiring_batches\nwith (security_invoker = true)')
  expect(sql).toContain('grant select on public.v_expiring_batches to authenticated;')
  expect(sql).toContain('create table if not exists public.error_reports')
  expect(sql).toContain('create table if not exists public.consignments')
  expect(sql).toContain('create table if not exists public.consignment_items')
  expect(sql.indexOf('create table if not exists public.consignment_items'))
    .toBeLessThan(sql.indexOf('alter table public.consignment_items add column if not exists expected_qty integer'))
  expect(sql.indexOf('create table if not exists public.consignment_items'))
    .toBeLessThan(sql.indexOf('returns public.consignment_items'))
  expect(sql).toContain('create or replace function public.create_consignment_manifest')
  expect(sql).toContain('create or replace function public.add_consignment_item')
  expect(sql).toContain('create or replace function public.finalize_consignment_receipt')
  expect(sql).toContain('create or replace function public.record_consignment_scan')
  expect(sql).toContain('and italy_packed_qty <> expected_qty')
  expect(sql).toContain('create or replace function public.transition_pasabuy_request')
  expect(sql).toContain('create or replace function public.submit_order_request')
  expect(sql).toContain('alter table public.orders add column if not exists customer_name text')
  expect(sql).toContain('alter table public.orders add column if not exists customer_email text')
  expect(sql).toContain('alter table public.orders add column if not exists total_amount numeric')
  expect(sql).toContain('create or replace function public.confirm_order_request')
  expect(sql).toContain('create or replace function public.mark_order_line_packed')
  expect(sql).toContain('create or replace function public.cancel_order_request')
  expect(sql).toContain('create or replace function public.fulfill_order_request')
  expect(sql).toContain('create or replace function public.verify_internal_channel_event')
  expect(sql).toContain('order by coalesce(expiry_date, best_before_date) asc nulls last, created_at asc')
  expect(sql).not.toContain('order by is_pinned desc')
  expect(sql).toContain('create policy orders_staff_read')
  expect(sql).not.toContain('create policy orders_staff_all')
  expect(sql).toContain('create policy products_authenticated_read')
  expect(sql).toContain('create policy error_reports_public_insert')
  expect(sql).toContain('create policy error_reports_staff_read')
  expect(sql).toContain('for select to anon\nusing (status::text')
  expect(sql).toContain('create or replace function public.set_user_role')
  expect(sql).toContain("if v_admin_count <= 1 then raise exception 'The final Admin cannot be demoted'")
  expect(sql).toContain('public.channel_connections, public.channel_credentials,')
  expect(sql).toContain('from anon, authenticated')
  expect(sql).toContain('grant select on public.products, public.globe_products, public.reviews\nto anon')
  expect(sql).toContain('public.user_profiles, public.globe_products, public.reviews,')
  expect(sql).toContain('create or replace function public.append_internal_message')
  expect(sql).toContain('create policy conversations_staff_read')
  expect(sql).toContain('create policy product_images_staff_insert')
  expect(sql).toContain('drop policy if exists product_images_public_read on storage.objects')
  expect(sql).toContain('drop policy if exists product_images_staff_insert on storage.objects')
  expect(sql).toContain('public.conversations, public.messages, public.staff_allocations,')
  expect(sql).not.toContain('grant select on public.staff_allocations')
  expect(sql).toContain("Stock changes must use batch reconciliation, receiving, reservation, or fulfillment")
  expect(sql).toContain("perform set_config('k2.allow_stock_write', 'on', true)")
  expect(sql).toContain('(greatest(on_hand - reserved - damaged - expired - unaccounted, 0)) stored,')
  expect(sql).toContain('alter table public.products add column if not exists title text')
  expect(sql).toContain('alter table public.products add column if not exists retail_price numeric')
  expect(sql).toContain('alter table public.products add column if not exists vip_price numeric')
  expect(sql).toContain('alter table public.products add column if not exists total_stock integer')
  expect(sql.indexOf('alter table public.products add column if not exists title text'))
    .toBeLessThan(sql.indexOf("set name = coalesce(nullif(name, ''), nullif(title, ''), sku)"))
  expect(sql).not.toMatch(/,\s*;/)
  expect(sql).toContain("display_name text,\n  status text not null default 'not_connected',")
  expect(sql).toContain("delete from public.products\nwhere sku in ('PAS-TRF-001'")
  expect(sql).toContain('Event history is append-only')
  expect(sql).not.toContain('FOR ALL TO public USING (true)')
})

test('product compatibility preflight supports both deployed schemas', async () => {
  const sql = await readFile(new URL('../supabase/migrations/20260802_product_compatibility_preflight.sql', import.meta.url), 'utf8')
  expect(sql).toContain('alter table public.products add column if not exists name text')
  expect(sql).toContain('alter table public.products add column if not exists title text')
  expect(sql).toContain('alter table public.products add column if not exists retail_price numeric')
  expect(sql).toContain('alter table public.products add column if not exists total_stock integer')
  expect(sql).toContain("select set_config('k2.allow_stock_write', 'on', true)")
  expect(sql.indexOf('add column if not exists title text'))
    .toBeLessThan(sql.indexOf("set name = coalesce(nullif(name, ''), nullif(title, ''), sku)"))
})

test('consignment preflight creates missing operational relations securely', async () => {
  const sql = await readFile(new URL('../supabase/migrations/20260802_consignment_compatibility_preflight.sql', import.meta.url), 'utf8')
  expect(sql).toContain('create table if not exists public.consignments')
  expect(sql).toContain('create table if not exists public.consignment_items')
  expect(sql.indexOf('create table if not exists public.consignments'))
    .toBeLessThan(sql.indexOf('create table if not exists public.consignment_items'))
  expect(sql).toContain('alter table public.consignments enable row level security')
  expect(sql).toContain('alter table public.consignment_items enable row level security')
  expect(sql).not.toContain('FOR ALL TO public USING (true)')
})

test('channel and admin preflight restores skipped late-stage relations', async () => {
  const sql = await readFile(new URL('../supabase/migrations/20260802_channel_admin_compatibility_preflight.sql', import.meta.url), 'utf8')
  for (const table of ['channel_listings', 'channel_credentials', 'staff_allocations', 'product_deletions', 'audit_logs', 'notifications']) {
    expect(sql).toContain(`create table if not exists public.${table}`)
    expect(sql).toContain(`alter table public.${table} enable row level security`)
  }
  expect(sql).not.toContain('FOR ALL TO public USING (true)')
})

test('continuous consignment scanners stay connected to server-enforced counts', async () => {
  const manager = await readFile(new URL('../src/views/admin/ConsignmentManager.jsx', import.meta.url), 'utf8')
  const scanner = await readFile(new URL('../src/views/admin/ConsignmentScannerModal.jsx', import.meta.url), 'utf8')
  const auditSql = await readFile(new URL('../supabase/migrations/20260804_restore_coupons_and_consignment_scanning.sql', import.meta.url), 'utf8')
  const hardeningSql = await readFile(new URL('../supabase/migrations/20260809_operations_hardening.sql', import.meta.url), 'utf8')

  expect(manager).toContain("import ConsignmentScannerModal from './ConsignmentScannerModal'")
  expect(manager).toContain("supabase.rpc('record_consignment_item_scan'")
  expect(manager).toContain('p_consignment_item_id: payload.itemId')
  expect(manager).toContain("setScannerStage('milan')")
  expect(manager).toContain("setScannerStage('manila')")
  expect(manager).toContain('Review and finalize')
  expect(scanner).toContain("import { Html5Qrcode } from 'html5-qrcode'")
  expect(scanner).toContain('lastReadRef')
  expect(scanner).toContain('await onScan(code, activeItemId || null)')
  expect(scanner).toContain('Barcode or SKU')
  expect(auditSql).toContain('create table if not exists public.consignment_scan_events')
  expect(auditSql).toContain("check (stage in ('milan', 'manila'))")
  expect(auditSql).toContain("raise exception 'Packed scans cannot exceed the expected manifest quantity'")
  expect(auditSql).toContain("raise exception 'Scanned quantity cannot exceed the packed manifest quantity'")
  expect(auditSql).toContain('insert into public.consignment_scan_events')
  expect(hardeningSql).toContain('create or replace function public.record_consignment_item_scan')
  expect(hardeningSql).toContain("raise exception 'SKU-only scans are ambiguous. Use record_consignment_item_scan with the selected box/lot line.'")
})

test('count-on-arrival truth is bounded by the Milan packed count', async () => {
  const sql = await readFile(new URL('../supabase/migrations/20260809_operations_hardening.sql', import.meta.url), 'utf8')

  expect(sql).toContain("if coalesce(p_expected_qty, 0) < 1 then raise exception 'Expected quantity must be positive'")
  expect(sql).toContain("if v_manifest.status <> 'Packing_Italy' then raise exception 'Manifest packing is closed'")
  expect(sql).toContain("if v_item.manila_scanned_qty >= v_item.italy_packed_qty then raise exception 'Received scans cannot exceed Milan packed quantity'")
  expect(sql).toContain('v_item.manila_scanned_qty, v_item.manila_scanned_qty, 0,')
  expect(sql).toContain('v_missing := v_item.italy_packed_qty - v_item.manila_scanned_qty')
  expect(sql).not.toContain("'surplus_on_arrival'")
})

test('coupon restoration is database-backed, private, limited, and auditable', async () => {
  const sql = await readFile(new URL('../supabase/migrations/20260804_restore_coupons_and_consignment_scanning.sql', import.meta.url), 'utf8')
  const manager = await readFile(new URL('../src/views/admin/CouponManager.jsx', import.meta.url), 'utf8')
  const admin = await readFile(new URL('../src/views/admin/Admin.jsx', import.meta.url), 'utf8')

  expect(sql).toContain('create table if not exists public.coupons')
  expect(sql).toContain("discount_type in ('percentage', 'fixed')")
  expect(sql).toContain('coupon_percentage_limit')
  expect(sql).toContain('coupon_window_valid')
  expect(sql).toContain('create or replace function public.validate_coupon')
  expect(sql).toContain('revoke all on table public.coupons from anon')
  expect(sql).toContain('create trigger coupons_audit_change')
  expect(manager).toContain("supabase.from('coupons')")
  expect(manager).toContain('Archive')
  expect(manager).not.toContain('deleteCoupon')
  expect(admin).toContain("coupons:           { label: 'Coupons'")
  expect(admin).toContain("section === 'coupons' ? <CouponManager />")
})

test('MAP-023 has a portable last-unit concurrency rehearsal', async () => {
  const packageJson = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'))
  expect(packageJson.scripts['rehearse:map023-last-unit'])
    .toBe('node scripts/rehearse-map023-last-unit-concurrency.mjs')

  const runner = await readFile(new URL('../scripts/rehearse-map023-last-unit-concurrency.mjs', import.meta.url), 'utf8')
  expect(runner).toContain('20260809_operations_hardening.sql')
  expect(runner).toContain('create or replace function public.confirm_order_request(')
  expect(runner).toContain("application_name='k2_last_unit_winner'")
  expect(runner).toContain('pg_stat_activity')
  expect(runner).toContain('Insufficient sellable lot stock')
  expect(runner).toContain('exactly one confirmed order')
})

test('MAP-023 rehearses an ambiguous confirmation retry without duplicate effects', async () => {
  const runner = await readFile(new URL('../scripts/rehearse-map023-last-unit-concurrency.mjs', import.meta.url), 'utf8')

  expect(runner).toContain("application_name='k2_ambiguous_confirmation_retry'")
  expect(runner).toContain('ambiguous-response baseline')
  expect(runner).toContain('same confirmed order returned without duplicate effects')
  expect(runner).toContain('AMBIGUOUS_RETRY_INVARIANT_MISMATCH')
})
