import fs from 'node:fs';import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {providerOperatingReplayPackage} from '../docs/evidence/20261004-category-shelf-life/operating-replay-package.mjs';
import {providerDeliveryFragments} from '../docs/evidence/20261004-category-shelf-life/build-express-delivery.mjs';
const root='D:/K2-Jimzon-local-recovery-32c52df326424b5a8b845c327824f4bc';
const before=JSON.parse(fs.readFileSync(root+'/oci-install-bounded01/execution01/before-catalog.json')),after=JSON.parse(fs.readFileSync(root+'/oci-install-bounded01/execution01/after-catalog.json'));
const saved=JSON.parse(fs.readFileSync(root+'/oci-envelope03/guarded-package.json'));
const prefix='\n  if (select jsonb_build_object(\'roles\'';const at=saved.sql.indexOf(prefix);assert.ok(at>=0);const end=saved.sql.indexOf(') is distinct from ',at);assert.ok(end>at);
const authoritySql=saved.sql.slice(at+'\n  if ('.length,end);
const fixed=providerDeliveryFragments({isolateFunctionDefaults:true,preserveCapturedStockViewAcl:true,preserveCapturedHandoverAcl:true,preserveCapturedReleaseAcls:true,preserveCapturedCompatibilityTriggerAcl:true,preserveCapturedReceivingAcls:true,preserveCapturedStaffAcls:true,financialRoleLock:true,boundedReferenceSeed:true});
const contractSql=fs.readFileSync('supabase/prepared/category_operating_schema_contract.sql','utf8').replace(/^--[^\n]*\n/gm,'').trim().replace(/;$/,'');
const input={contractSql,before,after,fragments:fixed.fragments,authoritySql,authority:saved.authority,managedAuthority:saved.managedAuthority,serverVersion:'170006'};
const result=providerOperatingReplayPackage({...input,qualifiedPlatformBarrier:true});
assert.equal(result.cutoverTables?.length,81,'candidate must retain all81 authority-compatible captured tables');
for(const r of before.relations.filter(r=>['r','p'].includes(r.kind)&&JSON.stringify(r)!==JSON.stringify(after.relations.find(a=>a.name===r.name))))assert.ok(result.cutoverTables.includes(r.name),'every changed original table remains locked: '+r.name);
assert.equal(result.protectedPlatformTables.length,7);
const changed=structuredClone(after);changed.relations.find(r=>r.name==='storage.migrations').owner='postgres';
assert.throws(()=>providerOperatingReplayPackage({...input,after:changed,qualifiedPlatformBarrier:true}),/PLATFORM_BARRIER/);
assert.throws(()=>providerOperatingReplayPackage({...input,fragments:[...fixed.fragments,'select 1;'],qualifiedPlatformBarrier:true}),/PLATFORM_BARRIER/);
const prior=providerOperatingReplayPackage(input);assert.equal(createHash('sha256').update(prior.sql).digest('hex'),saved.sqlSha256,'default package remains byte-identical');
console.log('PASS:81 complete barrier tables, every changed table retained,7 immutable platform records, payload/metadata drift refusal, unchanged default package');
