const peso = (value) => value == null
  ? 'Not recorded'
  : new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(Number(value) || 0)

export default function PackingSlipModal({ isOpen, onClose, order }) {
  if (!isOpen || !order) return null

  const reference = order.publicReference || order.id
  const packed = String(order.status).toLowerCase() === 'packed'

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-4 backdrop-blur-md" role="dialog" aria-modal="true" aria-labelledby="packing-slip-title">
      <div className="max-h-[92vh] w-full max-w-2xl space-y-5 overflow-y-auto rounded-adm bg-white p-6 text-slate-900 shadow-2xl">
        <div className="flex flex-col justify-between gap-3 border-b border-slate-200 pb-4 print:hidden sm:flex-row sm:items-center">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Internal document only</p>
            <h2 id="packing-slip-title" className="mt-1 text-xl font-bold">Packing record</h2>
          </div>
          <div className="flex gap-2">
            <button onClick={() => window.print()} className="min-h-11 rounded-adm-sm bg-slate-900 px-4 text-sm font-bold text-white hover:bg-slate-800">Print internal slip</button>
            <button onClick={onClose} aria-label="Close packing record" className="min-h-11 min-w-11 rounded-adm-sm bg-slate-100 px-3 text-slate-700 hover:bg-slate-200">Close</button>
          </div>
        </div>

        <div className="rounded border-2 border-slate-900 p-5 font-mono text-sm">
          <div className="flex flex-col justify-between gap-3 border-b-2 border-slate-900 pb-4 sm:flex-row">
            <div><p className="text-xs font-bold uppercase text-slate-500">K2 Jimzon internal packing record</p><p className="mt-1 text-lg font-bold">{reference}</p></div>
            <div className="sm:text-right"><p className="text-xs font-bold uppercase text-slate-500">Source</p><p className="font-bold">{order.channel || 'Not recorded'}</p></div>
          </div>

          <div className="my-4 rounded border border-amber-300 bg-amber-50 p-3 text-xs leading-relaxed text-amber-900">
            This is not a courier waybill and contains no carrier tracking number. Attach the real label generated by the marketplace or selected courier before handover.
          </div>

          <div className="grid gap-4 border-y border-slate-300 py-4 sm:grid-cols-2">
            <div><p className="text-xs font-bold uppercase text-slate-400">Ship from</p><p className="mt-1 font-bold">K2 Jimzon · Manila hub</p></div>
            <div><p className="text-xs font-bold uppercase text-slate-400">Recipient</p><p className="mt-1 font-bold">{order.customer}</p><p className="mt-1 text-xs text-slate-600">{order.deliveryAddress || 'Delivery address not present on this order line'}</p><p className="mt-1 text-xs text-slate-600">{order.customerPhone || order.customerEmail || 'Contact not present on this order line'}</p></div>
          </div>

          <table className="mt-4 w-full border-collapse text-left text-sm">
            <thead><tr className="border-b border-slate-300 bg-slate-100"><th className="p-2">SKU</th><th className="p-2">Product</th><th className="p-2 text-center">Qty</th><th className="p-2 text-right">Packing state</th></tr></thead>
            <tbody>{(order.items || []).map((item) => <tr key={item.sku} className="border-b border-slate-200"><td className="p-2 font-bold">{item.sku}</td><td className="p-2">{item.title}</td><td className="p-2 text-center font-bold">{item.qty}</td><td className="p-2 text-right font-bold">{packed ? 'Packed' : 'Pending scan'}</td></tr>)}</tbody>
          </table>

          <div className="mt-4 grid gap-3 border-t-2 border-slate-900 pt-4 text-xs sm:grid-cols-3">
            <div><p className="font-bold uppercase text-slate-400">Payment state</p><p className="mt-1 font-bold">{String(order.paymentStatus).replaceAll('_', ' ')}</p></div>
            <div><p className="font-bold uppercase text-slate-400">Recorded total</p><p className="mt-1 font-bold">{peso(order.total)}</p></div>
            <div><p className="font-bold uppercase text-slate-400">Handover method</p><p className="mt-1 font-bold">{order.courier || 'Not recorded'}</p></div>
          </div>
        </div>
      </div>
    </div>
  )
}
