// Versioned, read-only staff procedure contracts for MAP-023 acceptance.
// This registry describes operational truth; importing it never performs work.

export const STAFF_GUIDE_META = Object.freeze({
  version: '2026-08-30-draft.12',
  approvalStatus: 'DRAFT — NOT LOCKED',
  effectiveDate: null,
  authority: 'K2 Jimzon - Brain/OPERATIONS_LOGIC_AND_WORKFLOW.md',
  advisoryOnly: true,
})

export const PROCEDURE_STATUS = Object.freeze({
  ENABLED: 'ENABLED',
  MANUAL: 'MANUAL — EXTERNAL STEP',
  PREPARED: 'PREPARED — NOT ACTIVE',
  UNAVAILABLE: 'UNAVAILABLE — BLOCKED',
})

const OPS = 'Operations Rulebook'
const BFF = 'docs/runbooks/ADMIN_BFF_SECURITY_RUNBOOK.md'
const INTAKE = 'docs/runbooks/PRODUCT_INTAKE_RUNBOOK.md'

const defineProcedure = procedure => Object.freeze({
  version: STAFF_GUIDE_META.version,
  effectiveDate: STAFF_GUIDE_META.effectiveDate,
  ...procedure,
})

export const STAFF_PROCEDURES = Object.freeze([
  defineProcedure({
    id: 'product-metadata', title: 'Create, edit, or archive product metadata', category: 'Product master', section: 'inventory',
    covers: ['product.create', 'product.edit', 'product.archive'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Admin with AAL2 and the product-master capability'],
    prerequisites: ['Exact product evidence and variant identity', 'For archive/delete: the Staff & Roles four-digit Delete PIN prerequisite and impact review'],
    entryPoint: 'Sidebar → Inventory → Product Master or Sheet Mode',
    steps: ['Search before creating to prevent a duplicate SKU or variant.', 'Create an unpublished Draft or open the exact existing product.', 'Edit only reviewed metadata and record the specific reason.', 'Use the controlled archive/delete action only after impact and PIN checks.'],
    validationsAndBlockers: ['SKU/barcode/variant identity must be unique and evidence-backed.', 'The Admin BFF product boundary and production cutover are not active; direct browser writes are transitional.'],
    expectedState: 'One canonical product record is created or versioned; archive/delete has an attributable audit event; no stock or publication state changes implicitly.',
    forbiddenShortcuts: ['Do not create inventory through product metadata.', 'Do not reuse a SKU for a similar-looking variant.', 'Do not bypass the guarded command with a direct table write.'],
    recovery: ['On timeout, reopen the exact SKU and inspect server truth before retrying.', 'If evidence or identity conflicts, leave the product Draft and escalate for review.'],
    sources: [`${OPS} §3, §6, §22–24`, BFF, 'docs/runbooks/STAFF_PRODUCT_DELETION_SOP.md'],
  }),
  defineProcedure({
    id: 'product-intake-manual', title: 'Manual two-Project product intake', category: 'Product intake', section: 'inventory',
    covers: ['product.intake.manual', 'product.intake.fallback'], status: PROCEDURE_STATUS.MANUAL,
    authorizedRoles: ['Catalog staff may prepare; Admin approves canonical changes and publication'],
    prerequisites: ['Readable front, label/back, barcode, and exact-variant photos', 'Access to the private K2 Product Content and K2 Product Image Studio ChatGPT Projects'],
    entryPoint: 'Scan center → New product research → Smart Paste',
    steps: ['Generate the PRODUCT_JSON request and paste it into K2 Product Content with the evidence.', 'Paste the single returned JSON object into Smart Paste and review every fact, unknown, use, instruction, warning, SEO field, and media brief.', 'In K2 Product Image Studio, attach the real front-package photo and request PRIMARY and AFTER separately.', 'Upload each reviewed image to its matching slot and save an unpublished Draft.'],
    validationsAndBlockers: ['Unknown facts remain unknown; AI output is not evidence.', 'PRIMARY must preserve exact packaging; AFTER must follow approved use and truth constraints.'],
    expectedState: 'One resumable intake draft links evidence, reviewed content, and separately reviewed PRIMARY/AFTER candidates; inventory remains unchanged.',
    forbiddenShortcuts: ['Never let AI assign SKU, price, cost, stock, quantity, lot, expiry, custody, approval, or publication.', 'Never merge the content and image Projects or accept an image without the real package reference.'],
    recovery: ['If JSON fails validation, correct the response at its source or use manual fields; do not hand-edit malformed JSON into acceptance.', 'If either Project is unavailable, save the intake draft and continue with reviewed manual fields/images.'],
    sources: [`${OPS} §6`, INTAKE, 'docs/specs/CHATGPT_PRODUCT_JSON_PROJECT.md', 'docs/specs/CHATGPT_PRODUCT_IMAGE_PROJECT.md'],
  }),
  defineProcedure({
    id: 'product-intake-paid-api', title: 'Paid API product-content and image path', category: 'Product intake', section: 'inventory',
    covers: ['product.intake.paid_api'], status: PROCEDURE_STATUS.UNAVAILABLE,
    authorizedRoles: ['Owner-authorized staff after spend controls and production activation'],
    prerequisites: ['Owner-approved confirmation sequence, model/provider, budget limits, retention policy, server-side secret, and activation evidence'],
    entryPoint: 'No operational Admin entry point exists yet',
    steps: ['Do not call a paid provider from the current Admin.', 'Use the manual K2 Product Content → Smart Paste → K2 Product Image Studio fallback until activation.', 'After activation, staff must deliberately select the paid path and confirm the priced scope before any call.'],
    validationsAndBlockers: ['Block content and image calls when budget, evidence, or required confirmation is missing.', 'Generated output must pass the same schema and human review as the manual path.'],
    expectedState: 'No provider call and no canonical product change occurs while this path is unavailable; the manual fallback remains available.',
    forbiddenShortcuts: ['Never place an API key in browser code or a VITE_ variable.', 'Never infer consent to spend from opening intake or uploading evidence.'],
    recovery: ['If a future call times out, recover by operation ID and provider receipt before retrying.', 'If cost or output scope differs, stop before image generation and return to manual intake.'],
    blocker: 'Owner confirmation design, spend ceiling, provider/model choice, retention policy, server boundary, and production activation are not yet approved and verified (see OWNER-007).',
    sources: [`${OPS} §6, §23–24`, INTAKE, 'MASTER_ACTION_PLAN.md → MAP-018 and MAP-023'],
  }),
  defineProcedure({
    id: 'paid-ai-spend-controls', title: 'Review and change paid AI spend controls', category: 'Security', section: 'staff_permissions',
    covers: ['ai.paid_controls'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['SuperAdmin only with AAL2; the owner controls SuperAdmin assignment'],
    prerequisites: ['Owner-approved provider/model snapshot', 'Per-product, per-session, and monthly hard caps', 'Retention/monitoring/rollback decision and a specific change reason'],
    entryPoint: 'Sidebar → Staff & Roles → Paid AI intake spending controls',
    steps: ['Review the current version and fail-closed state.', 'Change only the approved model or hard-cap values.', 'Type ENABLE_PAID_AI when deliberately enabling the paid path.', 'Save an attributable reason and verify the new version; keep the manual two-Project path available.'],
    validationsAndBlockers: ['The server—not the browser—requires SuperAdmin and AAL2.', 'Enabling requires a model plus ordered non-zero caps; content/image confirmations and manual fallback cannot be disabled.', 'The control remains unavailable until the prepared migration, server boundary, provider, and owner decisions are activated and verified.'],
    expectedState: 'One versioned, audited configuration records the model, caps, actor, reason, and fail-closed/available state; changing it does not create products or inventory.',
    forbiddenShortcuts: ['Do not assign SuperAdmin through the ordinary staff role selector.', 'Do not put provider keys in browser code or VITE_ variables.', 'Do not treat a saved control as proof that a provider call or deployment is live.'],
    recovery: ['On version conflict, refresh and review the newest configuration before retrying.', 'If provider, budget, or output evidence is unavailable, disable/leave disabled and use the manual workflow.'],
    blocker: 'The control is prepared locally but remains blocked by OWNER-007 provider/model, retention, activation, and production evidence.',
    sources: [`${OPS} §6, §22–24`, 'MASTER_ACTION_PLAN.md → MAP-018', 'K2 Jimzon - Brain/OWNER_QUESTIONS.md → OWNER-007'],
  }),
  defineProcedure({
    id: 'sales-computation', title: 'Read sales truth and calculate a planning scenario', category: 'Sales', section: 'overview',
    covers: ['sales.compute'], status: PROCEDURE_STATUS.ENABLED,
    authorizedRoles: ['Authenticated Admin BOS staff with access to Command center'],
    prerequisites: ['For recorded totals: canonical order requests in the selected 7/30/90-day period', 'For planning: reviewed quantity or planned-profit target, price, unit cost, discount or target margin, other/fixed peso costs, and payment/channel percentage rate'],
    entryPoint: 'Sidebar → Command center → Sales computation summary; floating Tools → Sales planner',
    steps: ['Choose the reporting period and read submitted-request, payment-verified, and fulfilled values separately.', 'Reconcile the four Payment × fulfillment buckets; together they must reproduce every request and peso in the selected period.', 'Open verified-not-fulfilled records for fulfillment follow-up and fulfilled-payment-not-verified records for payment-state review.', 'Select Review records, choose any exact fact filter, and reconcile the displayed subtotal with the source rows.', 'Use Download CSV only when a customer-free selected-period operational extract is needed; verify the filename names the period and filter.', 'Treat Settled payouts and Actual profit as unavailable until their named canonical records exist.', 'Open Admin tools and select Sales planner.', 'Use Check a price to enter fixed peso fees and the channel fee percentage separately; review goods, other/fixed, percentage-fee, total-cost, profit, margin, markup, and the upward-cent-rounded fee-aware break-even result.', 'Use Find target price to solve the minimum planned unit price from quantity, unit cost, total discount, other/fixed costs, gross-sales percentage fee, and target gross margin; then review the recomputed achieved scenario.', 'Use Find max discount to solve the total discount ceiling from a chosen price, reviewed costs, gross-sales percentage fee, and target gross margin; use only the downward-cent-rounded allowance and review the recomputed achieved scenario.', 'Use Find units needed to solve the minimum whole units for a positive planned-profit target; verify the recomputed result meets the target and the immediately previous quantity remains below it.', 'For a valid result, use Copy planning summary only after reviewing its timestamp, mode, assumptions, complete result, and opening planning-only warning; keep that warning attached when pasting into a discussion.', 'Approve or change a real product price or promotion only through the canonical Product Master workflow.'],
    validationsAndBlockers: ['A request is not a verified payment; a verified payment is not a fulfilled order or settled payout.', 'The reconciliation buckets are mutually exclusive and their count/value sums must equal all selected-period requests.', 'Payment not verified means only payment_status is not exactly verified; do not relabel it unpaid, missing, failed, or lost.', 'One record can be both payment-verified and fulfilled; the ordinary drilldown filters are exact facts, not mutually exclusive stages.', 'The CSV contains only date, internal reference, channel, order/payment states, and request value; it is not a backup, settlement, accounting book, or profit report.', 'All four planner modes reject negative/non-finite values; entered quantity must be whole.', 'Fixed fees are peso amounts; channel fee rate is applied to gross sales before discount in all four modes.', 'Check a price must solve break-even using the percentage fee rate, not freeze the fee calculated at the proposed price.', 'Target gross margin is planned profit divided by net sales after discount.', 'Target margin and channel fee rate must each stay within 0–99.99%; target-price mode additionally requires their sum below 100%.', 'Find max discount must stop when the chosen price misses the target even at zero discount.', 'Find units needed requires positive per-unit contribution and a result no greater than 100,000 units.', 'Copy planning summary is unavailable for invalid calculations and contains no customer fields; copying changes clipboard text only.', 'Planner results are not approved prices/promotions, quotas, promised outcomes, or recorded financial/tax truth.'],
    expectedState: 'Staff reads status-separated canonical order totals, downloads one non-posting customer-free selected-period extract, checks one proposed price with automatic percentage fees and a true upward-cent-rounded break-even, obtains one upward-cent-rounded target-price recommendation, obtains one downward-cent-rounded total-discount ceiling, obtains one minimum whole-unit planned-profit target with previous-unit proof, or copies one timestamped customer-free planning handoff; no product price, promotion, quota, order, payment, cost, payout, tax, inventory, or accounting record changes.',
    forbiddenShortcuts: ['Do not report the planner result, copied summary, or CSV as approved price/promotion, actual profit, landed cost, accounting, settlement, or backup truth.', 'Do not remove the planning-only warning or assumptions when pasting a copied summary.', 'Do not copy a target-price or maximum-discount result directly into canonical product data without the normal review/approval workflow.', 'Do not round a maximum-discount result upward or exceed its total allowance by multiplying a rounded per-unit display.', 'Do not treat the whole-unit result as an assigned quota, inventory reservation, order, or guaranteed profit.', 'Do not add customer contact data or unreviewed columns to the export.', 'Do not treat unavailable payout/profit as zero.', 'Do not combine submitted, verified, fulfilled, and settled values into one unlabeled sales number.'],
    recovery: ['Refresh Command center if a source is marked unavailable, the four buckets do not reproduce the selected-period total, or a visible subtotal does not reconcile; do not substitute zero.', 'Review the exact payment evidence/status before interpreting a fulfilled-payment-not-verified row.', 'Change the period if more than the newest 25 matching records need row-level review.', 'Correct invalid planning inputs or return to the source records before recalculating.', 'If clipboard copy fails, allow clipboard access and retry; otherwise keep the visible assumptions/results together when transcribing manually.', 'If target margin plus fee rate reaches 100% or the target-price recommendation exceeds the supported range, stop and revise the planned assumptions rather than forcing a price.', 'If the chosen price cannot preserve the target margin without discount, revise the price, costs, fee, or target before considering a promotion.', 'If unit contribution is non-positive or more than 100,000 units are required, revise the price, cost, fee, or profit target rather than forcing a quantity.', 'Escalate actual-profit or settlement reporting until exact-lot cost snapshots and a canonical payout ledger exist.'],
    sources: [`${OPS} §16–17, §24`, 'MASTER_ACTION_PLAN.md → MAP-023'],
  }),
  defineProcedure({
    id: 'first-inventory', title: 'Add first inventory from an allowed source', category: 'Inventory', section: 'inventory',
    covers: ['inventory.first.flight', 'inventory.first.supplier', 'inventory.first.adjustment'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Inventory staff for receipt/count; Admin for controlled adjustment approval'],
    prerequisites: ['Existing canonical product', 'Exact source evidence: flight/box manifest, approved supplier receipt, or authorized opening-count reason'],
    entryPoint: 'Flight Consignments for flight stock; supplier receipt remains unavailable; Inventory → lot reconciliation for an authorized opening count',
    steps: ['Choose the source before entering quantity.', 'Create or select the exact lot with batch, expiry, hub, owner, and custodian evidence.', 'Physically count and record the accepted quantity through the source-specific command.', 'Verify the resulting lot and immutable inventory event.'],
    validationsAndBlockers: ['Product import never creates quantity.', 'Supplier-direct receipt has no complete canonical command and remains unavailable.', 'Counts below active reservations or missing required expiry evidence are blocked.'],
    expectedState: 'One exact lot and attributable inventory event establish physical quantity, source, location, owner, custodian, and eligibility; the product record itself is unchanged.',
    forbiddenShortcuts: ['Do not type stock into product metadata or a spreadsheet.', 'Do not label a generic adjustment as a flight or supplier receipt.'],
    recovery: ['On ambiguous save, inspect the lot and event history before retrying with the same operation context.', 'Quarantine questionable units rather than guessing eligibility.'],
    sources: [`${OPS} §5, §7, §9–10`, INTAKE, BFF],
  }),
  defineProcedure({
    id: 'flight-receive-recount', title: 'Receive and independently recount a flight box', category: 'Receiving', section: 'consignment',
    covers: ['inventory.receive', 'inventory.recount'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Assigned Milan packer; independent Manila receiver; Admin for exception resolution'],
    prerequisites: ['Exact flight, box, and manifest lines', 'Physical units and usable scan/typed-code input'],
    entryPoint: 'Sidebar → Flight Consignments → exact manifest → Milan or Manila scanner',
    steps: ['Milan selects the exact flight and box and scans every packed unit once.', 'Seal/transit only through valid states.', 'Manila selects the arriving box and scans every physical unit independently.', 'Compare expected, packed, and received counts; classify every difference before finalization.'],
    validationsAndBlockers: ['Manila must not copy Milan totals.', 'Wrong, damaged, unexpected, unknown-expiry, and insufficient-shelf-life units cannot enter sellable stock.'],
    expectedState: 'Durable scan events and a receipt preserve expected, packed, received, accepted, discrepant, and quarantined quantities; accepted inventory finalizes exactly once.',
    forbiddenShortcuts: ['Do not bulk-complete an uncounted box.', 'Do not rescan after timeout until persisted scan truth is checked.'],
    recovery: ['Resume the same manifest/box and operation identity.', 'Keep unresolved units in exception or quarantine and escalate instead of forcing finalization.'],
    sources: [`${OPS} §7, §9`, BFF],
  }),
  defineProcedure({
    id: 'lot-reconcile-edit', title: 'Reconcile or edit an exact inventory lot', category: 'Inventory', section: 'inventory',
    covers: ['inventory.reconcile', 'inventory.edit'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Authorized inventory staff; Admin approval where disposition or clearance requires it'],
    prerequisites: ['Exact SKU/lot/batch/expiry/hub/owner/custodian identity', 'Physical recount, active reservation context, record version, and specific reason'],
    entryPoint: 'Sidebar → Inventory → batch details / reconciliation',
    steps: ['Open the exact lot and review reservations and event history.', 'Enter the physical count, evidence, and specific reconciliation reason.', 'Review server-derived available/sellable consequences.', 'Submit once and verify before/after balances plus the immutable event.'],
    validationsAndBlockers: ['A count below reservations is blocked.', 'Availability is derived; it is not an editable independent field.'],
    expectedState: 'The exact lot has one versioned physical-balance change and immutable before/after reconciliation event; reservations and custody remain consistent.',
    forbiddenShortcuts: ['Do not overwrite stock from Sheet Mode or CSV.', 'Do not use a generic reason or edit quantity_available directly.'],
    recovery: ['On stale version, refresh and recount/review instead of overwriting.', 'On timeout, inspect lot version and events before retrying the same signed command.'],
    sources: [`${OPS} §5, §10, §24`, 'docs/runbooks/CATALOG_SPREADSHEET_RUNBOOK.md', BFF],
  }),
  defineProcedure({
    id: 'lot-custody-transfer', title: 'Offer and complete an exact-lot custody transfer', category: 'Inventory', section: 'omni_hub',
    covers: ['inventory.transfer'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Authorized sender and a separate authorized receiver'],
    prerequisites: ['Exact lot, quantity, source/destination hub and custodian', 'Available unoffered units and a specific transfer reason'],
    entryPoint: 'Sidebar → Fulfillment Hub → custody/handover tools',
    steps: ['Sender offers an exact quantity from one lot.', 'Receiver independently counts and accepts or rejects.', 'Resolve partial or disputed quantities explicitly.', 'Verify current-holder and custody-history views.'],
    validationsAndBlockers: ['Offered units cannot be sold or transferred again.', 'Sender action alone cannot change final custody.'],
    expectedState: 'Accepted, rejected, cancelled, or partial transfer state records both actors, locations, quantities, reason, time, and immutable custody/balance events.',
    forbiddenShortcuts: ['Do not reassign a whole box without equivalent per-lot evidence.', 'Do not change free-text custodian fields as a substitute for acceptance.'],
    recovery: ['Receiver rejects mismatched units and records the discrepancy.', 'For ambiguous timeout, inspect transfer state and events before same-key retry.'],
    sources: [`${OPS} §10`, BFF],
  }),
  defineProcedure({
    id: 'lot-disposition', title: 'Quarantine, clear, or write off exact units', category: 'Inventory', section: 'inventory',
    covers: ['inventory.quarantine', 'inventory.clear', 'inventory.write_off'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Inventory staff may quarantine; Admin/approved authority clears or writes off'],
    prerequisites: ['Exact lot and quantity', 'Damage/expiry/identity evidence, reason, and any required approval'],
    entryPoint: 'Sidebar → Inventory → expiry exceptions / batch details',
    steps: ['Quarantine questionable units immediately without changing identity.', 'Investigate and attach evidence.', 'Choose the authorized disposition: return to eligible stock, disclosed clearance, supplier return, or write-off.', 'Verify sellable quantity and immutable event consequences.'],
    validationsAndBlockers: ['Expired, 0–30 day, damaged, unknown-date expiry-tracked, or unresolved units cannot be cleared for ordinary sale.', 'Write-off and clearance require the appropriate capability and reason.'],
    expectedState: 'The exact units have one attributable disposition and event; quarantined/written-off units are excluded from sellable stock and approved cleared units follow FEFO rules.',
    forbiddenShortcuts: ['Do not delete a lot to hide a variance.', 'Do not change product status or spreadsheet stock as a disposition.'],
    recovery: ['If evidence is incomplete, keep units quarantined.', 'If the wrong disposition was recorded, open an authorized corrective event; never erase history.'],
    sources: [`${OPS} §5, §10, §15`, BFF],
  }),
  defineProcedure({
    id: 'product-publication', title: 'Publish or unpublish reviewed product content', category: 'Product master', section: 'inventory',
    covers: ['product.publish', 'product.unpublish'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['AAL2 Admin with publication capability'],
    prerequisites: ['Reviewed product identity, public copy, media rights/evidence, usage/warnings, SEO, and eligible stock wording'],
    entryPoint: 'Sidebar → Inventory → exact product → publication controls',
    steps: ['Review the exact public projection and media.', 'Resolve missing, conflicting, or unsupported claims.', 'Publish through the explicit guarded action or withdraw/unpublish with a reason.', 'Verify the storefront projection separately.'],
    validationsAndBlockers: ['Draft creation or correction never publishes implicitly.', 'Globe visibility does not equal publication.'],
    expectedState: 'Publication state and immutable event change explicitly; storefront exposes only reviewed published fields, or removes withdrawn content after verification.',
    forbiddenShortcuts: ['Do not toggle a browser flag or edit the database directly.', 'Do not describe local or seeded content as publicly verified.'],
    recovery: ['Withdraw questionable content first, preserve evidence, correct to Draft, and republish only after review.', 'If storefront verification fails, keep the product unpublished/withdrawn and investigate deployment/cache truth.'],
    sources: [`${OPS} §6`, BFF, 'docs/runbooks/DEPLOYMENT_RUNBOOK.md'],
  }),
  defineProcedure({
    id: 'order-exceptions', title: 'Resolve order, payment, packing, or delivery exceptions', category: 'Orders', section: 'omni_hub',
    covers: ['order.exception', 'payment.exception', 'packing.exception', 'delivery.exception'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Fulfillment staff for evidence; authorized verifier for payment/refund/disposition decisions'],
    prerequisites: ['Exact canonical order/request and customer identity', 'Payment, packing scan, delivery, communication, and lot/reservation evidence as applicable'],
    entryPoint: 'Sidebar → Fulfillment Hub → exact order; Messages for linked communication',
    steps: ['Open the exact order before scanning or changing state.', 'Classify cancellation, payment rejection/timeout, short/wrong pack, failed delivery, return, exchange, or refund.', 'Record the authorized decision and exact inventory/payment consequences.', 'Reconcile reservations, lots, payment/settlement, delivery, and customer communication.'],
    validationsAndBlockers: ['Payment evidence is not verified payment.', 'A provider/courier label or delivery result is real only with its receipt.'],
    expectedState: 'One canonical order and linked case/events show the decision, money effect, exact-unit disposition, communication state, and next owner without stranded reservation.',
    forbiddenShortcuts: ['Do not mark paid from a screenshot alone.', 'Do not scan a product before selecting an order.', 'Do not invent a courier waybill, message delivery, refund, or stock release.'],
    recovery: ['For timeout, inspect server/provider truth and reuse operation identity.', 'Keep uncertain money or units pending/quarantined until evidence reconciles.'],
    sources: [`${OPS} §12–16, §19, §24`, BFF],
  }),
  defineProcedure({
    id: 'pasabuy-wholesale', title: 'Handle Pasabuy and wholesale work without inventing terms', category: 'Sales', section: 'pasabuy_manager',
    covers: ['pasabuy', 'wholesale'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Staff may capture/research; owner or authorized commercial approver sets terms and price'],
    prerequisites: ['Customer/buyer identity and exact request', 'Evidence for source, costs, availability, quote terms, and approvals'],
    entryPoint: 'Sidebar → Pasabuy Quotes; Sidebar → Customers/Wholesale for inquiries',
    steps: ['Record the request and missing information.', 'Research the exact item and costs.', 'Save a versioned quote or approved terms with owner rationale.', 'Record acceptance before purchase; then track purchase, shipment, receipt, allocation, payment, delivery, and exceptions separately.'],
    validationsAndBlockers: ['Wholesale inquiry capture cannot grant wholesale pricing or authority.', 'No universal deposit, refund, discount, handling fee, or quote-duration rule is assumed.'],
    expectedState: 'The request/inquiry, approved terms, acceptance, canonical order, stock, payment, delivery, and exceptions remain linked and separately attributable.',
    forbiddenShortcuts: ['Do not unlock wholesale pricing from a browser flag or contact match.', 'Do not promise sourcing, price, deadline, or refund before approval.'],
    recovery: ['Version a changed quote; never overwrite the accepted history.', 'If the buyer or terms cannot be verified, keep the case unapproved and escalate.'],
    sources: [`${OPS} §8, §17, §19`, 'docs/runbooks/GUEST_COMMERCE_BFF_RUNBOOK.md', BFF],
  }),
  defineProcedure({
    id: 'customer-messages', title: 'Handle customer messages and internal notes', category: 'Communication', section: 'inbox',
    covers: ['customer.messages'], status: PROCEDURE_STATUS.MANUAL,
    authorizedRoles: ['Assigned staff with conversation access'],
    prerequisites: ['Verified customer/channel identity and linked order/request when relevant'],
    entryPoint: 'Sidebar → Messages; use each external platform app while its connector is unavailable',
    steps: ['Read the persisted conversation and linked facts.', 'Reply in the verified external channel when no adapter exists.', 'Record commitments as an internal note linked to the operational record.', 'Treat delivery as confirmed only with provider evidence.'],
    validationsAndBlockers: ['Internal notes must never be exposed as customer messages.', 'Messenger, Instagram, WhatsApp, Viber, TikTok, Lazada, and external sends are not integrated.'],
    expectedState: 'Canonical notes and conversation state reflect verified facts; external delivery remains provider-specific and is not claimed without a receipt.',
    forbiddenShortcuts: ['Do not call copied text sent.', 'Do not claim a social message reached K2 systems when no adapter ingests it.'],
    recovery: ['On uncertain send, check the external platform before retrying.', 'Record failed/unknown delivery and retain the exact conversation context.'],
    sources: [`${OPS} §19`, BFF],
  }),
  defineProcedure({
    id: 'staff-security', title: 'Invite staff and maintain least-privilege access', category: 'Security', section: 'staff_permissions',
    covers: ['staff.security'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Owner/Admin with AAL2 and staff-management capability'],
    prerequisites: ['Verified staff Gmail identity, minimum required role, MFA/recovery readiness, and approval reason'],
    entryPoint: 'Sidebar → Staff & Roles',
    steps: ['Invite the exact identity.', 'Assign only the minimum role/capabilities.', 'Verify the staff session and privileged denial/allow behavior.', 'Remove or reduce access promptly when duties end or risk changes.'],
    validationsAndBlockers: ['Browser visibility is not authorization; the server enforces capability and AAL.', 'The owner verification Gmail must have 2-Step Verification and current recovery evidence before launch acceptance.'],
    expectedState: 'The authenticated staff identity has only approved server-enforced capabilities and attributable access events.',
    forbiddenShortcuts: ['Do not share accounts, passwords, recovery codes, delete PINs, or provider tokens.', 'Do not place privileged credentials in browser storage or VITE_ variables.'],
    recovery: ['Revoke the affected session/access first, then follow the incident/key-rotation runbook.', 'For invitation ambiguity, inspect the durable invitation/status record before retrying.'],
    sources: [`${OPS} §22–23`, BFF, 'docs/runbooks/SECURITY_INCIDENT_AND_KEY_ROTATION_RUNBOOK.md'],
  }),
  defineProcedure({
    id: 'channel-readiness', title: 'Assess and activate one channel capability at a time', category: 'Channels', section: 'integrations',
    covers: ['channel.readiness'], status: PROCEDURE_STATUS.PREPARED,
    authorizedRoles: ['Owner/Admin for credentials and activation; operations staff for reconciliation evidence'],
    prerequisites: ['Approved provider app/shop ID/scopes', 'Server-only secrets, exact channel vocabulary, listing mappings, stock allocation rule, and test plan'],
    entryPoint: 'Sidebar → Channel Readiness and Workflow Graph → Channels & Integrations',
    steps: ['Assess credentials, ingress, orders, listings, stock, messages, waybills, and health separately.', 'Enable only one approved capability.', 'Run one real signed/provider operation and reconcile its canonical records.', 'Mark only that capability ready after failure/retry evidence.'],
    validationsAndBlockers: ['One webhook does not make an entire channel live.', 'Two shops require separate credentials and listing rows while sharing canonical inventory truth.'],
    expectedState: 'Each capability has truthful ready/manual/unavailable state and provider/canonical evidence; no independent stock or order truth is created.',
    forbiddenShortcuts: ['Never expose provider secrets in VITE_ variables.', 'Never label a capability live from a mock, fixture, copied response, or file check.'],
    recovery: ['Stop the affected capability, preserve event/receipt evidence, reconcile, then retry idempotently.', 'Continue in the Seller Center when the adapter is unavailable.'],
    sources: [`${OPS} §11, §23–24`, 'docs/specs/CONNECTOR_INTEGRATION_SPEC.md', BFF],
  }),
  defineProcedure({
    id: 'backup-incident-rollback', title: 'Back up, respond to an incident, and roll back safely', category: 'Safety', section: 'overview',
    covers: ['backup', 'incident', 'rollback'], status: PROCEDURE_STATUS.MANUAL,
    authorizedRoles: ['Owner/incident lead; authorized technical operator for commands and provider changes'],
    prerequisites: ['Named system/change and owner', 'Approved encrypted backup destination and separately stored passphrase/recovery access', 'Prior deployment/migration identity and rollback criteria'],
    entryPoint: 'No ordinary staff mutation screen; follow the named backup, deployment, or incident runbook',
    steps: ['Stop or contain the risky operation and preserve minimal evidence.', 'Take and verify the required database and Storage backup before approved change.', 'Apply only the scoped recovery/rollback and verify schema, permissions, data, artifacts, domains, and provider state separately.', 'Record what remains unverified and the next action in the owning MAP item.'],
    validationsAndBlockers: ['Backup artifact verification does not prove owner account recovery.', 'A web rollback must not restore database state unless the separate restore decision is approved.'],
    expectedState: 'The incident/change has attributable evidence, a verified recovery result or explicit unresolved blocker, and no silent loss of canonical history.',
    forbiddenShortcuts: ['Do not expose secrets in logs/chat.', 'Do not overwrite an existing backup or claim a prepared rollback was applied.', 'Do not restore broadly before impact is understood.'],
    recovery: ['Escalate when backup, passphrase, owner recovery, or provider identity cannot be verified.', 'Use the last verified clean artifact/state and re-run exact postflight checks.'],
    sources: ['docs/runbooks/DATABASE_BACKUP_AND_RESTORE_RUNBOOK.md', 'docs/runbooks/DEPLOYMENT_RUNBOOK.md', 'docs/runbooks/SECURITY_INCIDENT_AND_KEY_ROTATION_RUNBOOK.md'],
  }),
  defineProcedure({
    id: 'unavailable-integrations', title: 'Operate honestly when an integration is unavailable', category: 'Channels', section: 'integrations',
    covers: ['integration.unavailable'], status: PROCEDURE_STATUS.UNAVAILABLE,
    authorizedRoles: ['Staff may use the verified provider portal; only Owner/Admin may activate connectors'],
    prerequisites: ['Exact capability and provider identified', 'Verified manual portal access if work must continue'],
    entryPoint: 'Sidebar → Channel Readiness; then the provider Seller Center/courier/messaging portal',
    steps: ['Confirm the exact capability says unavailable/manual.', 'Perform only the permitted action in the verified provider portal.', 'Record the resulting commitment or receipt against the canonical K2 record when supported.', 'Escalate connector activation through the owning MAP item.'],
    validationsAndBlockers: ['Lazada/TikTok order adapters, social messaging ingestion, external message send, stock synchronization, automatic courier labels, supplier receipt, and paid AI intake are not active.', 'No provider capability becomes ready without credentials, scopes, receipts, failure recovery, and real end-to-end reconciliation.'],
    expectedState: 'No provider call and no canonical integration state is fabricated; manual work is explicitly recorded as manual and unsupported canonical state remains unchanged.',
    forbiddenShortcuts: ['Do not create fake webhook, waybill, sent-message, stock-sync, or API-success records.', 'Do not paste provider secrets into the browser or guide.'],
    recovery: ['If manual/provider truth and K2 records disagree, stop, preserve both references, and open reconciliation.', 'Keep the capability unavailable until a real end-to-end postflight passes.'],
    blocker: 'The named provider adapters, credentials/scopes, production activation, and end-to-end receipts are incomplete per Channel Readiness and the active MAP.',
    sources: [`${OPS} §11, §13, §19, §23–24`, 'docs/specs/FUTURE_INTEGRATIONS.md', BFF],
  }),
])
